<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class TmbdgtPlafond extends Model
{
    protected $table = 'tmbdgtplafond';

    /**
     * @param  Builder<Model>  $q
     */
    public function scopeForKontrak(Builder $q, string $orgContr, string $iContr): Builder
    {
        return $q->where('c_org_contr', $orgContr)->where('i_contr', $iContr);
    }

    protected $fillable = [
        'c_source',
        'c_org_id',
        'c_org',
        'c_org_contr',
        'i_contr',
        'c_bdgt_contrstat',
        'c_bdgt_contrinex',
        'c_bdgt_anggaran',
        'c_pgm',
        'c_pgm_sub',
        'c_pgm_ver',
        'c_coa_dr',
        'c_coa_cr',
        'c_cy',
        'v_bdgt_month1',
        'v_bdgt_month2',
        'v_bdgt_month3',
        'v_bdgt_month4',
        'v_bdgt_month5',
        'v_bdgt_month6',
        'v_bdgt_month7',
        'v_bdgt_month8',
        'v_bdgt_month9',
        'v_bdgt_month10',
        'v_bdgt_month11',
        'v_bdgt_month12',
        'v_bdgt_total',
        'v_bdgt_addmonth1',
        'v_bdgt_addmonth2',
        'v_bdgt_addmonth3',
        'v_bdgt_addmonth4',
        'v_bdgt_addmonth5',
        'v_bdgt_addmonth6',
        'v_bdgt_addmonth7',
        'v_bdgt_addmonth8',
        'v_bdgt_addmonth9',
        'v_bdgt_addmonth10',
        'v_bdgt_addmonth11',
        'v_bdgt_addmonth12',
        'v_bdgt_plantotal',
        'v_bdgt_addtotal',
        'v_bdgt_saldomonth1',
        'v_bdgt_saldomonth2',
        'v_bdgt_saldomonth3',
        'v_bdgt_saldomonth4',
        'v_bdgt_saldomonth5',
        'v_bdgt_saldomonth6',
        'v_bdgt_saldomonth7',
        'v_bdgt_saldomonth8',
        'v_bdgt_saldomonth9',
        'v_bdgt_saldomonth10',
        'v_bdgt_saldomonth11',
        'v_bdgt_saldomonth12',
        'v_bdgt_saldototal',
        'i_entry',
        'd_entry',
        'c_org_center',
        'c_org_dit',
        'c_bdgt_cat',
        'v_bdgt_planmonth1',
        'v_bdgt_planmonth2',
        'v_bdgt_planmonth3',
        'v_bdgt_planmonth4',
        'v_bdgt_planmonth5',
        'v_bdgt_planmonth6',
        'v_bdgt_planmonth7',
        'v_bdgt_planmonth8',
        'v_bdgt_planmonth9',
        'v_bdgt_planmonth10',
        'v_bdgt_planmonth11',
        'v_bdgt_planmonth12',
        'c_stat_bdgt',
        'i_ref_updbdgt',
        'd_ref_updbdgt',
        'c_bdgt_stat',
        'i_pmn',
        'd_pmn',
        'i_order',
    ];

    protected function casts(): array
    {
        return [
            'c_bdgt_anggaran' => 'integer',
            'c_pgm_ver' => 'string',
            'v_bdgt_addmonth1' => 'integer',
            'v_bdgt_addmonth2' => 'integer',
            'v_bdgt_addmonth3' => 'integer',
            'v_bdgt_addmonth4' => 'integer',
            'v_bdgt_addmonth5' => 'integer',
            'v_bdgt_addmonth6' => 'integer',
            'v_bdgt_addmonth7' => 'integer',
            'v_bdgt_addmonth8' => 'integer',
            'v_bdgt_addmonth9' => 'integer',
            'v_bdgt_addmonth10' => 'integer',
            'v_bdgt_addmonth11' => 'integer',
            'v_bdgt_addmonth12' => 'integer',
            'v_bdgt_plantotal' => 'integer',
            'v_bdgt_addtotal' => 'integer',
            'v_bdgt_month1' => 'integer',
            'v_bdgt_month2' => 'integer',
            'v_bdgt_month3' => 'integer',
            'v_bdgt_month4' => 'integer',
            'v_bdgt_month5' => 'integer',
            'v_bdgt_month6' => 'integer',
            'v_bdgt_month7' => 'integer',
            'v_bdgt_month8' => 'integer',
            'v_bdgt_month9' => 'integer',
            'v_bdgt_month10' => 'integer',
            'v_bdgt_month11' => 'integer',
            'v_bdgt_month12' => 'integer',
            'v_bdgt_total' => 'integer',
            'v_bdgt_planmonth1' => 'integer',
            'v_bdgt_planmonth2' => 'integer',
            'v_bdgt_planmonth3' => 'integer',
            'v_bdgt_planmonth4' => 'integer',
            'v_bdgt_planmonth5' => 'integer',
            'v_bdgt_planmonth6' => 'integer',
            'v_bdgt_planmonth7' => 'integer',
            'v_bdgt_planmonth8' => 'integer',
            'v_bdgt_planmonth9' => 'integer',
            'v_bdgt_planmonth10' => 'integer',
            'v_bdgt_planmonth11' => 'integer',
            'v_bdgt_planmonth12' => 'integer',
            'v_bdgt_saldomonth1' => 'integer',
            'v_bdgt_saldomonth2' => 'integer',
            'v_bdgt_saldomonth3' => 'integer',
            'v_bdgt_saldomonth4' => 'integer',
            'v_bdgt_saldomonth5' => 'integer',
            'v_bdgt_saldomonth6' => 'integer',
            'v_bdgt_saldomonth7' => 'integer',
            'v_bdgt_saldomonth8' => 'integer',
            'v_bdgt_saldomonth9' => 'integer',
            'v_bdgt_saldomonth10' => 'integer',
            'v_bdgt_saldomonth11' => 'integer',
            'v_bdgt_saldomonth12' => 'integer',
            'v_bdgt_saldototal' => 'integer',
            'd_entry' => 'string',
            'd_ref_updbdgt' => 'string',
            'd_pmn' => 'string',
            'created_at' => 'datetime',
            'updated_at' => 'datetime',
        ];
    }
}
